### ISSUE TITLE
Línea del tiempo 

### ISSUE THREAD

**Issue by Dasus2332** [SistemasTecTlaxiaco/actividad-7-Dasus2332#1]
[Linea del tiempo (web) Lazo López Jesús Danery.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-Dasus2332/files/9854707/Linea.del.tiempo.web.Lazo.Lopez.Jesus.Danery.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Hola comapñerto para tu siguiente trabajo porfavor usa un tipo de letra más legible y justifica el texto, 17%.

**Comment by Daisy-GonzalezLita12** [comment]
Hola compañero para tu siguiente trabajo por favor usa un tipo de letra más legible y justifica el texto, 17%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
